title: Mark Berthelemy
name: Mark Berthelemy

description: 'Learning and knowledge systems consultant'
simple_description: 'Learning and knowledge systems consultant'
long-description: 'Experienced and independent learning systems consultant helping you to reduce risk, improve efficiency and deliver more quickly.'
sub-description: 'Connecting the dots to business success'

url: https://mark.berthelemy.net
domain: mark.berthelemy.net

collections_dir: collections

collections:
  lessons:
    output: false # switched off
    permalink: /:collection/:path
  toolkit:
    output: false
    permalink: /:collection/:path
  expertise:
    output: false
    sort_by: order
    permalink: /:collection/:path

levels-order:
 - Novice
 - Intermediate
 - Advanced

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Mark Berthelemy

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      sitemap: true
  - scope:
      path: ""
      type: "drafts"
    values:
      sitemap: false
  - scope:
      type: "lessons"
    values:
      layout: lesson
      style: style1
      sitemap: false
  - scope:
      type: "toolkit"
    values:
      layout: tool
      sitemap: false
  - scope:
      path: ""
      type: "expertise"
    values:
      layout: expertise
  - scope:
      path: "/google*"
    values:
      sitemap: false
