title: Mark Berthelemy

description: 'Learning and knowledge systems consultant'
simple_description: 'Learning and knowledge systems consultant'
long-description: 'Experienced and independent learning systems consultant helping you to reduce risk, improve efficiency and deliver more quickly.'
sub-description: 'Connecting the dots to business success'

url: https://mark.berthelemy.net
domain: mark.berthelemy.net



include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-feed

author: Mark Berthelemy

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/mark-portrait.png"
  # author will appear under the avatar (optional)
  author: "Mark Berthelemy"
  # tagline will appear under the title (optional)
  tagline: "A multifaceted professional"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  description: "Always happy to talk about education, technology, music and living in Brittany / Il est toujours heureux de parler d'éducation, de technologie, de musique et de la vie en Bretagne."
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: 
